---
- name: pull jenkins container
  docker_image:
    name: hackwish/jenkins-dockercap
  when: docker_installed is success

- name: Create mount volume directories for persistent data
  file: path={{ item.path }} state=directory mode="a+rw"
  with_items:
      - { path: '/opt/jenkins' }

- name: Run Jenkins
  docker_container:
    name: jenkins
    image: jenkins/jenkins:lts
    restart_policy: unless-stopped
    ports:
     - "8080:8080"
     - "50000:50000"
    env:
      JAVA_OPTS: -Dhudson.footerURL=https://www.i-med.cl
      RANCHER_NETWORK: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - $HOME/ssh/id_rsa:$HOME/.ssh/id_rsa 
      # - $HOME/ssh/id_rsa.pub:$HOME/.ssh/id_rsa.pub
      - /opt/jenkins:/var/jenkins_home
